FROM python:3.10-slim

WORKDIR /app

# This image must have prefect in it
COPY requirements/data-science.requirements.txt /app/
RUN pip install --no-cache-dir -r data-science.requirements.txt
COPY pyproject.toml .
COPY src /app/src
RUN pip install --no-cache-dir --no-deps .

COPY gx /app/gx