artifact_location: file:///C:/Users/bm2bw/Downloads/ivado_final_project/project_code/src/mlflows/random_forest_model/0
creation_time: 1707415057815
experiment_id: '0'
last_update_time: 1707415057815
lifecycle_stage: active
name: Default
