artifact_location: file:///C:/Users/bm2bw/Downloads/ivado_final_project/project_code/src/scripts/model/0
creation_time: 1707501166177
experiment_id: '0'
last_update_time: 1707501166177
lifecycle_stage: active
name: Default
